/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import libreria.Autor;
import libreria.BaseDatosControlador;
import libreria.Categoria;
import libreria.Editorial;
import libreria.Herramientas;
import libreria.Libro;
import libreria.Tema;
import libreria.Tools;
import libreria.Util;
import proyectogui.clsGestionArchivo;

/**
 *
 * @author David
 */
public class AgregarLibro extends javax.swing.JPanel implements Tools{

    /**
     * Creates new form Default
     */
    public AgregarLibro() {
        initComponents();
        Modificar = false;
        initComponent();
    }

    public AgregarLibro(Libro libroTemporal) {
        initComponents();
        this.Modificar = true;
        this.LibroModificable = libroTemporal;
        initComponent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jD_Autor = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jD_Tema = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel19 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Categoria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Editorial = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Verde = new javax.swing.JButton();
        Rojo = new javax.swing.JButton();

        jD_Autor.setTitle("Agregar Autores");
        jD_Autor.setLocation(new java.awt.Point(300, 100));
        jD_Autor.setMinimumSize(new java.awt.Dimension(738, 468));
        jD_Autor.setModal(true);
        jD_Autor.setResizable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setPreferredSize(new java.awt.Dimension(48, 185));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/flechaD.png"))); // NOI18N
        jLabel7.setToolTipText("Añadir");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/flechaI.png"))); // NOI18N
        jLabel8.setToolTipText("Eliminar");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Pais", "F° Nacimin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Pais");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("F° Nacimin");
        }

        jLabel5.setBackground(new java.awt.Color(0, 0, 102));
        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingresados");
        jLabel5.setOpaque(true);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel6.setBackground(new java.awt.Color(0, 0, 102));
        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Seleccione para Ingresar");
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton5.setText("Aceptar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Restaurar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jD_AutorLayout = new javax.swing.GroupLayout(jD_Autor.getContentPane());
        jD_Autor.getContentPane().setLayout(jD_AutorLayout);
        jD_AutorLayout.setHorizontalGroup(
            jD_AutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_AutorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jD_AutorLayout.setVerticalGroup(
            jD_AutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_AutorLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jD_AutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jD_Tema.setTitle("Agregar Temas");
        jD_Tema.setLocation(new java.awt.Point(300, 100));
        jD_Tema.setMinimumSize(new java.awt.Dimension(738, 468));
        jD_Tema.setModal(true);
        jD_Tema.setResizable(false);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setPreferredSize(new java.awt.Dimension(48, 185));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/flechaD.png"))); // NOI18N
        jLabel9.setToolTipText("Añadir");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/flechaI.png"))); // NOI18N
        jLabel10.setToolTipText("Eliminar");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod_Tema", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel11.setBackground(new java.awt.Color(0, 0, 102));
        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Ingresados");
        jLabel11.setOpaque(true);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList2);

        jLabel19.setBackground(new java.awt.Color(0, 0, 102));
        jLabel19.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Seleccione para Ingresar");
        jLabel19.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton8.setText("Aceptar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Cancelar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Restaurar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jD_TemaLayout = new javax.swing.GroupLayout(jD_Tema.getContentPane());
        jD_Tema.getContentPane().setLayout(jD_TemaLayout);
        jD_TemaLayout.setHorizontalGroup(
            jD_TemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_TemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jD_TemaLayout.setVerticalGroup(
            jD_TemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_TemaLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jD_TemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setBackground(new java.awt.Color(0, 0, 51));
        setMaximumSize(new java.awt.Dimension(900, 579));
        setMinimumSize(new java.awt.Dimension(900, 579));
        setPreferredSize(new java.awt.Dimension(900, 579));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese Los datos Correspodientes");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 620, 38));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/foto.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51), 3));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingrese una Imagen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 430));

        Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        Categoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CategoriaFocusGained(evt);
            }
        });
        add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 150, 22));

        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, 25, 52));

        jLabel12.setOpaque(true);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 25, 52));

        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 25, 52));

        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 25, 52));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Tema(s)");
        jLabel15.setOpaque(true);
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 150, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Autor(es)");
        jLabel16.setOpaque(true);
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 150, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Editorial");
        jLabel17.setOpaque(true);
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 150, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Categoria");
        jLabel18.setOpaque(true);
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 150, 20));

        Editorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        Editorial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EditorialFocusGained(evt);
            }
        });
        add(Editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 150, 22));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 150, 22));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 150, 22));

        Verde.setBackground(new java.awt.Color(51, 255, 51));
        Verde.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Verde.setText("Agregar Libro");
        Verde.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51)));
        Verde.setFocusPainted(false);
        Verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerdeActionPerformed(evt);
            }
        });
        add(Verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 130, 38));

        Rojo.setBackground(new java.awt.Color(255, 51, 51));
        Rojo.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Rojo.setText("Restaurar");
        Rojo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        Rojo.setFocusPainted(false);
        Rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RojoActionPerformed(evt);
            }
        });
        add(Rojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 38));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        rutaarchivo.setFileFilter(new FileNameExtensionFilter("Imagenes", "jpg","png","gif","jpeg","JPG"));
        int estado = rutaarchivo.showDialog(null, "Abrir Archivo");
        if(estado==JFileChooser.APPROVE_OPTION){
            archivo = rutaarchivo.getSelectedFile();
            if(archivo.canRead()){
                if (archivo.getName().endsWith(".jpg")||
                        archivo.getName().endsWith(".png")||
                        archivo.getName().endsWith(".gif")||
                        archivo.getName().endsWith(".jpeg")||
                        archivo.getName().endsWith(".JPG")){
                    byteImg = vgestion.abrirImagen(archivo);
                    ImageIcon icon = new ImageIcon(byteImg);
                    Imagen = icon;
                    icon = new ImageIcon(icon.getImage().getScaledInstance(250, 360, 0));
                    jLabel2.setIcon(icon);
                } else
                    Herramientas.Error("Solo se permiten archivos Imagen.", "Formato no permitido");
            } else 
                Herramientas.Error("Error al intentar cargar el archivo", "Archivo corrupto");
        } else if (estado!=JFileChooser.CANCEL_OPTION) {
            Herramientas.Error("Buscador de archivos no funciona", "Lo sentimos");
        }
    }//GEN-LAST:event_jLabel2MousePressed

    private void VerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerdeActionPerformed
        Libro nuevo = Datos.getLibro();
        if (nuevo!=null) {
            if (Autores.size()>0) {
                nuevo.setListaAutores(Autores);
                if (Temas.size()>0){
                    nuevo.setListaTemas(Temas);
                    if (!Editorial.getItemAt(Editorial.getSelectedIndex()).equals("") &&
                            !Editorial.getItemAt(Editorial.getSelectedIndex()).equals("Seleccionar")) {
                        Editorial e = EDITORIALES.get(Editorial.getSelectedIndex());
                        nuevo.setEditorial(new Editorial(e));
                        if (!Categoria.getItemAt(Categoria.getSelectedIndex()).equals("") &&
                                !Categoria.getItemAt(Categoria.getSelectedIndex()).equals("Seleccionar")) {
                            Categoria c = CATEGORIAS.get(Categoria.getSelectedIndex());
                            nuevo.setCategoria(new Categoria(c));
                            String ruta = "/src/Image/";
                            if (Imagen!=null) {
                                nuevo.setImagen(Imagen);
                            }else if (Modificar){
                                nuevo.setImagen(LibroModificable.getImagen());
                            }else{
                                File file = new File("./"+ruta+"foto.jpg");
                                byteImg = vgestion.abrirImagen(file);
                                ImageIcon icon = new ImageIcon(byteImg);
                                Imagen = icon;
                                nuevo.setImagen(Imagen);
                            }
                            ruta += nuevo.getIbsn()+".png";
                            File file = new File("./" + ruta);
                            if (Modificar) {
                                if (Imagen!=null) {
                                    file.delete();
                                    file = new File("./" + ruta);
                                    vgestion.guardarImagen(file, byteImg);
                                }
                                Util.ActualizaLibro(nuevo);
                                Herramientas.mensage("Has modificado el Libro", "Modificacion de Libro Exitosa");
                            }else{
                                vgestion.guardarImagen(file, byteImg);
                                LIBROS.add(nuevo);
                                BaseDatosControlador.GUARDARSTOCK(nuevo.getEjemplares());
                                BaseDatosControlador.GUARDARLIBRO(nuevo);
                                Herramientas.mensage("Has ingresado el Libro", "Ingreso de Libro Exitoso");
                            }
                        } else Herramientas.Error("No has seleccionado la Categoria", "Especifique la Categoria");
                    } else Herramientas.Error("No has seleccionado la Editorial", "Especifique la Editorial");
                } else Herramientas.Error("No has ingresado los Tema(s)", "Especifique el Tema");
            }
            else Herramientas.Error("No has ingresado el Autor(es)", "Especifique el Autor");
        }
    }//GEN-LAST:event_VerdeActionPerformed

    private void RojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RojoActionPerformed
        if (Modificar) {
            initComponent();
        } else {
            Datos.Reset();
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/foto.jpg")));
        }
    }//GEN-LAST:event_RojoActionPerformed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        new Ventana(new AgregarAutor()).setVisible(true);
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        cargarAutoresLista();
    }//GEN-LAST:event_jLabel7MousePressed
    private void cargarAutoresLista(){
        int[] array = jList1.getSelectedIndices();
        AutorSelec.clear();
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        int x = table.getRowCount();
        for (int i = 0; i < x; i++) {
            table.removeRow(0);
        }
        for (int i: array) {
            String[] s = AUTORES.get(i).getListaIngresados().split(",");
            AutorSelec.add(new Autor(AUTORES.get(i)));
            table.addRow(new Object[]{s[0],s[1],s[2],s[3]});
        }
    }
    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        int[] array = jTable1.getSelectedRows();
        int[] arrays = new int[array.length];
        for (int i = arrays.length-1; i >= 0; i--) {
            arrays[i]=array[(arrays.length-1)-i];
        }
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        for (int i : arrays) {
            table.removeRow(i);
            AutorSelec.remove(i);
        }
    }//GEN-LAST:event_jLabel8MousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (AutorSelec.size()>0) {
           Autores = AutorSelec;
           jD_Autor.dispose();
        } else {
            jD_Autor.setModal(false);
            Herramientas.Error("No has ingresado ningún Autor", "Ingrese el Autor(es)");
            jD_Autor.setModal(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jD_Autor.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        int x = table.getRowCount();
        for (int i = 0; i < x; i++) {
            table.removeRow(0);
        }
        Autores = new ArrayList<>();
        AutorSelec.clear();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CargarAutores();
        jD_Autor.setLocationRelativeTo(null);
        jD_Autor.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        new Ventana(new AgregarEditorial()).setVisible(true);
    }//GEN-LAST:event_jLabel13MousePressed

    private void EditorialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EditorialFocusGained
        cargarEditoriales();
    }//GEN-LAST:event_EditorialFocusGained
    private void cargarEditoriales(){
        String[] Arrayeditorial = new String[EDITORIALES.size()];
        for (int i = 0; i < EDITORIALES.size(); i++) {
            Arrayeditorial[i] = EDITORIALES.get(i).getNombre();
        }
        Editorial.setModel(new javax.swing.DefaultComboBoxModel<>(Arrayeditorial));
    }
    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        new AgregarCategoria().setVisible(true);
    }//GEN-LAST:event_jLabel14MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        new AgregarTema().setVisible(true);
    }//GEN-LAST:event_jLabel4MousePressed

    private void CategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CategoriaFocusGained
        cargarCategorias();
    }//GEN-LAST:event_CategoriaFocusGained
    private void cargarCategorias(){
        String[] Arraycategorias = new String[CATEGORIAS.size()];
        for (int i = 0; i < CATEGORIAS.size(); i++) {
            Arraycategorias[i] = CATEGORIAS.get(i).getNombre();
        }
        Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(Arraycategorias));
    }
    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        cargarListaTemas();
    }//GEN-LAST:event_jLabel9MousePressed
    private void cargarListaTemas(){
        int[] array = jList2.getSelectedIndices();
        TemaSelec.clear();
        DefaultTableModel table = (DefaultTableModel) jTable2.getModel();
        int x = table.getRowCount();
        for (int i = 0; i < x; i++) {
            table.removeRow(0);
        }
        for (int i: array) {
            String[] s = TEMAS.get(i).getListaIngresados().split(",");
            TemaSelec.add(new Tema(TEMAS.get(i)));
            table.addRow(new Object[]{s[0],s[1]});
        }
    }
    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        int[] array = jTable2.getSelectedRows();
        int[] arrays = new int[array.length];
        for (int i = arrays.length-1; i >= 0; i--) {
            arrays[i]=array[(arrays.length-1)-i];
        }
        DefaultTableModel table = (DefaultTableModel) jTable2.getModel();
        for (int i : arrays) {
            table.removeRow(i);
            TemaSelec.remove(i);
        }
    }//GEN-LAST:event_jLabel10MousePressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (TemaSelec.size()>0) {
           Temas = TemaSelec;
           jD_Tema.dispose();
        } else {
            jD_Tema.setModal(false);
            Herramientas.Error("No has ingresado ningún Tema", "Ingrese el Tema(s)");
            jD_Tema.setModal(true);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jD_Tema.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        DefaultTableModel table = (DefaultTableModel) jTable2.getModel();
        int x = table.getRowCount();
        for (int i = 0; i < x; i++) {
            table.removeRow(0);
        }
        Temas = new ArrayList<>();
        TemaSelec.clear();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CargarTemas();
        jD_Tema.setLocationRelativeTo(null);
        jD_Tema.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CargarAutores(){
        /*AUTORES.add(new Autor("Dc", "David", "Campos", "Costa Rica", 1989, "Inteligente"));
        AUTORES.add(new Autor("Ac", "ale", "Campos", "Panama", 1992, "Inteligente"));
        AUTORES.add(new Autor("Ec", "Edgar", "Chs", "Africa", 1950, "Inteligente"));*/
        String listaAutore[] = new String[AUTORES.size()];
        for (int i = 0; i < AUTORES.size(); i++) {
            listaAutore[i] = AUTORES.get(i).getLista();
        }
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() {
                return listaAutore.length;
            }
            @Override
            public String getElementAt(int i) {
                return listaAutore[i];
            }
        });
    }
    
    private void CargarTemas(){
        /*TEMAS.add(new Tema("tb", "Bases de Datos"));
        TEMAS.add(new Tema("tr", "Reposteria"));
        TEMAS.add(new Tema("tp", "Progarmacion"));*/
        String[] listaTemas = new String[TEMAS.size()];
        for (int i = 0; i < TEMAS.size(); i++) {
            listaTemas[i] = TEMAS.get(i).getNombre();
        }
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() {
                return listaTemas.length;
            }
            @Override
            public String getElementAt(int i) {
                return listaTemas[i];
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Categoria;
    private javax.swing.JComboBox<String> Editorial;
    private javax.swing.JButton Rojo;
    private javax.swing.JButton Verde;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jD_Autor;
    private javax.swing.JDialog jD_Tema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
    private PestañasLibro Datos;
    private JFileChooser rutaarchivo;
    private clsGestionArchivo vgestion;
    private File archivo;
    private byte[] byteImg;
    private ArrayList<Autor> AutorSelec;
    private ArrayList<Autor> Autores;
    private ArrayList<Tema> Temas;
    private ArrayList<Tema> TemaSelec;
    private ImageIcon Imagen;
    private final boolean Modificar;
    private Libro LibroModificable;
    
    private void initComponent() {
        this.rutaarchivo = new JFileChooser();
        this.vgestion = new clsGestionArchivo();
        this.AutorSelec = new ArrayList<>();
        this.Autores = new ArrayList<>();
        this.Temas = new ArrayList<>();
        this.TemaSelec = new ArrayList<>();
        this.Imagen = null;
        if (Modificar) {
            this.Datos = new PestañasLibro(Modificar);
            this.add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 520, 430));
            Autores = LibroModificable.getListaAutores();
            Temas = LibroModificable.getListaTemas();
            jLabel2.setIcon(new ImageIcon(LibroModificable.getImagen().getImage().getScaledInstance(250, 360, 0)));
            Verde.setText("Modificar");
            cargarEditoriales();
            cargarCategorias();
            Categoria.setSelectedItem(LibroModificable.getCategoria().getNombre());
            Editorial.setSelectedItem(LibroModificable.getEditorial().getNombre());
            CargarAutores();
            int[] indices = new int[LibroModificable.getListaAutores().size()];
            int o = 0;
            for (int i = 0; i < AUTORES.size(); i++) {
                for (Autor listaAutore : LibroModificable.getListaAutores()) {
                    if (AUTORES.get(i).getCod_Autor().equals(listaAutore.getCod_Autor())) {
                        indices[o]=i;
                    }
                }
            }
            jList1.setSelectedIndices(indices);
            cargarAutoresLista();
            CargarTemas();
            indices = new int[LibroModificable.getListaTemas().size()];
            o = 0;
            for (int i = 0; i < TEMAS.size(); i++) {
                for (Tema listaTema : LibroModificable.getListaTemas()) {
                    if (TEMAS.get(i).getCod_Tema().equals(listaTema.getCod_Tema())) {
                        indices[o]=i;
                    }
                }
            }
            jList2.setSelectedIndices(indices);
            cargarListaTemas();
            Datos.Cargardatos(LibroModificable);
        }else {
            this.Datos = new PestañasLibro();
            this.add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 520, 430));
        }
    }
}
