/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Component;
import libreria.BaseDatosControlador;
import libreria.Editorial;
import libreria.Herramientas;
import libreria.Tools;
import libreria.Util;

/**
 *
 * @author David
 */
public class AgregarEditorial extends javax.swing.JPanel implements Tools{

    /**
     * Creates new form Default
     */
    public AgregarEditorial() {
        initComponents();
        pais.setModel(new javax.swing.DefaultComboBoxModel<>(Util.getPaises()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ceditorial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        telefono = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pais = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ciudad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(30, 30, 51));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(900, 580));
        setMinimumSize(new java.awt.Dimension(900, 580));
        setPreferredSize(new java.awt.Dimension(900, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setVisible(false);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 180, 50));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Restaurar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 180, 50));

        jButton3.setBackground(new java.awt.Color(0, 0, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 180, 50));

        ceditorial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ceditorial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ceditorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 69, 153), 2));
        ceditorial.setMaximumSize(new java.awt.Dimension(366, 50));
        ceditorial.setMinimumSize(new java.awt.Dimension(366, 50));
        ceditorial.setPreferredSize(new java.awt.Dimension(366, 50));
        add(ceditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 340, 40));

        jLabel2.setBackground(new java.awt.Color(17, 17, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText(" Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 218, 40));

        nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 69, 153), 2));
        nombre.setMaximumSize(new java.awt.Dimension(366, 50));
        nombre.setMinimumSize(new java.awt.Dimension(366, 50));
        nombre.setPreferredSize(new java.awt.Dimension(366, 50));
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 340, 40));

        telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 69, 153), 2));
        try {
            telefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 340, 40));

        jLabel3.setBackground(new java.awt.Color(17, 17, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText(" Telefono");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 218, 40));

        jLabel1.setBackground(new java.awt.Color(17, 17, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText(" Cod_Editorial");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 218, 40));

        pais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pais.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 69, 153), 2));
        add(pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 340, 40));

        jLabel4.setBackground(new java.awt.Color(17, 17, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText(" Pais");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 218, 40));

        ciudad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ciudad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ciudad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 69, 153), 2));
        ciudad.setMaximumSize(new java.awt.Dimension(366, 50));
        ciudad.setMinimumSize(new java.awt.Dimension(366, 50));
        ciudad.setPreferredSize(new java.awt.Dimension(366, 50));
        add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 340, 40));

        jLabel5.setBackground(new java.awt.Color(17, 17, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText(" Ciudad");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 218, 40));

        jLabel6.setBackground(new java.awt.Color(17, 17, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText(" Dirección");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 218, 40));

        direccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        direccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 69, 153), 2));
        direccion.setMaximumSize(new java.awt.Dimension(366, 50));
        direccion.setMinimumSize(new java.awt.Dimension(366, 50));
        direccion.setPreferredSize(new java.awt.Dimension(366, 50));
        add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 340, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ingrese la Editorial");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Herramientas.ResetCampos(new Component[] {ceditorial,nombre,telefono,ciudad,direccion});
        pais.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (Herramientas.ValidarCampos(new Component[] {ceditorial,nombre,ciudad,direccion})) {
            EDITORIALES.add(new Editorial(ceditorial.getText(),nombre.getText(),
                    (!"".equals(telefono.getText().trim()))?Integer.parseInt(telefono.getText()):0,
                    Util.getPais(pais.getSelectedIndex()),
                    ciudad.getText(),
                    direccion.getText()));
            BaseDatosControlador.GUARDAREDITORIAL(EDITORIALES.getLast());
        } else { 
            Herramientas.Error("No has llenado todos los campos\nAsegurate de llenar bien la información", "Campos Vacios");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        v.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
   

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ceditorial;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> pais;
    private javax.swing.JFormattedTextField telefono;
    // End of variables declaration//GEN-END:variables

    private Ventana v;

    public void setV(Ventana v) {
        this.v = v;
        this.jButton1.setVisible(true);
    }
}
