/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Component;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import libreria.BaseDatosControlador;
import libreria.Cliente;
import libreria.Detalle;
import libreria.Factura;
import libreria.Herramientas;
import libreria.Libro;
import libreria.Util;

/**
 *
 * @author David
 */
public class Ventas extends javax.swing.JPanel implements libreria.Tools{

    /**
     * Creates new form Default
     */
    public Ventas() {
        initComponents();
        initComponent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogFactura = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        area = new javax.swing.JTextArea();
        Registrar = new javax.swing.JButton();
        Hora = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Detalle = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        Cancelar = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Cedula = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Apellido1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Apellido2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Telefono = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ISBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JSpinner();
        Eliminar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        Facturar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Monto_Paga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Impuesto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Subtotal = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();

        jDialogFactura.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogFactura.setTitle("Factura");
        jDialogFactura.setBackground(new java.awt.Color(0, 0, 0));
        jDialogFactura.setResizable(false);
        jDialogFactura.setType(java.awt.Window.Type.UTILITY);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Factura.png"))); // NOI18N
        jLabel2.setMinimumSize(new java.awt.Dimension(2, 2));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(2, 2));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanel6.setLayout(flowLayout1);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        area.setEditable(false);
        area.setColumns(2);
        area.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        area.setRows(2);
        area.setBorder(null);
        area.setMinimumSize(new java.awt.Dimension(2, 2));
        area.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDialogFactura.getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        setBackground(new java.awt.Color(0, 28, 71));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setMaximumSize(new java.awt.Dimension(900, 579));
        setMinimumSize(new java.awt.Dimension(900, 579));
        setPreferredSize(new java.awt.Dimension(900, 579));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registrar.setBackground(new java.awt.Color(51, 204, 255));
        Registrar.setText("Registar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 24, -1, -1));

        Hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hora.setText("jLabel2");
        add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 25, 120, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Hora:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 4, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Nuevo Cliente");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 4, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FacturaFondo.png"))); // NOI18N
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        Detalle.setBackground(new java.awt.Color(224, 239, 255));
        Detalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Articulo", "Precio Uni..", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Detalle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Detalle.setFillsViewportHeight(true);
        Detalle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Detalle);
        if (Detalle.getColumnModel().getColumnCount() > 0) {
            Detalle.getColumnModel().getColumn(0).setResizable(false);
            Detalle.getColumnModel().getColumn(0).setPreferredWidth(340);
            Detalle.getColumnModel().getColumn(1).setResizable(false);
            Detalle.getColumnModel().getColumn(2).setResizable(false);
            Detalle.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 580, 396));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(300, 416));
        jPanel4.setMinimumSize(new java.awt.Dimension(300, 416));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 416));

        Cancelar.setBackground(new java.awt.Color(51, 204, 255));
        Cancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Aceptar.setBackground(new java.awt.Color(51, 204, 255));
        Aceptar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(51, 204, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Cedula:");
        jLabel10.setOpaque(true);

        Cedula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CedulaFocusLost(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(178, 235, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nombre:");
        jLabel11.setOpaque(true);

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel12.setBackground(new java.awt.Color(178, 235, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Primer Apellido:");
        jLabel12.setOpaque(true);

        Apellido1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel13.setBackground(new java.awt.Color(178, 235, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Segundo Apellido:");
        jLabel13.setOpaque(true);

        Apellido2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel14.setBackground(new java.awt.Color(178, 235, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Telefono:");
        jLabel14.setOpaque(true);

        try {
            Telefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Telefono.setText("");
        Telefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cedula)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellido1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Apellido2)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(Telefono)))
                    .addComponent(Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(Telefono))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(Apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, -346, 300, 416));
        jPanel4.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Codigo ISBN");

        ISBN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cantidad");

        Cantidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        Eliminar.setBackground(new java.awt.Color(51, 204, 255));
        Eliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("Eliminar");
        Eliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 204, 255), null));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Agregar.setBackground(new java.awt.Color(51, 204, 255));
        Agregar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Agregar.setForeground(new java.awt.Color(255, 255, 255));
        Agregar.setText("Agregar");
        Agregar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 204, 255), null));
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Facturar.setBackground(new java.awt.Color(178, 235, 255));
        Facturar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Facturar.setText("Facturar");
        Facturar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 204, 255), null));
        Facturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total:");

        Monto_Paga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Paga con:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Facturar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ISBN)
                    .addComponent(Monto_Paga, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Cantidad)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Monto_Paga, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Facturar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 300, 416));

        jPanel2.setBackground(new java.awt.Color(153, 228, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Impuesto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        Impuesto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Impuesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Impuesto.setText("4785");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Impuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Impuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 280, 50));

        jPanel3.setBackground(new java.awt.Color(122, 220, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SubTotal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        Subtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Subtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtotal.setText("4785");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 280, 50));

        Total.setBackground(new java.awt.Color(51, 204, 255));
        Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 0, 0));
        Total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Total.setText("7896546545");
        Total.setOpaque(true);
        add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 300, 59));
    }// </editor-fold>//GEN-END:initComponents

    private void CedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CedulaFocusLost
        String cedula = Cedula.getText();
        if (!cedula.equals("")) {
            for (Cliente cliente : CLIENTES) {
                if(cliente.getCedula().equals(cedula)){
                    cli = cliente;
                    Nombre.setText(cli.getNombre());
                    Apellido1.setText(cli.getApellido1());
                    Apellido2.setText(cli.getApellido2());
                    Telefono.setText(String.valueOf(cli.getTelefono()));
                    break;
                }
            }
        }
    }//GEN-LAST:event_CedulaFocusLost

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        if (Herramientas.ValidarCampos(new Component[]{Cedula,Nombre,Apellido1,Apellido2,Telefono})) {
            if (cli.getCedula().equals("000000000")) {
                cli = new Cliente(Cedula.getText(),Nombre.getText(),Apellido1.getText(),Apellido2.getText(),Integer.parseInt(Telefono.getText()));
                factura.setClient(cli);
            }else
                factura.setClient(cli);
            ocultar();
        } else 
            Herramientas.Error("No has llenado todos los datos", "Ingrese los datos solicitados");
    }//GEN-LAST:event_AceptarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        cli = Util.getClienteDefault();
        factura.setClient(cli);
        ocultar();
    }//GEN-LAST:event_CancelarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        if (!ISBN.getText().equals("")) {
            Libro l = Util.getLibro(ISBN.getText());
            if (l!=null) {
                if (l.getEjemplares().facturable(Integer.valueOf(Cantidad.getValue().toString()))) {
                    factura.addDetalle(new Detalle(factura.getCod_Factura(), l, Integer.valueOf(Cantidad.getValue().toString())));
                    ActualizaTabla();
                }else   
                    Herramientas.Error("No se dispone la cantidad solicitada\nsolo se pueden vender "+l.getEjemplares().getCantidad_Almacenada(), "Faltan existencias");
            }else{
                Herramientas.Error("Este libro no se encuentra registrado", "Libro no existe");
            }
        } else 
            Herramientas.Error("Ingrese un ISBN y seleccione la cantidad deseada", "Faltan datos");
    }//GEN-LAST:event_AgregarActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        mostrar();
    }//GEN-LAST:event_RegistrarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int seleccionada = Detalle.getSelectedRow();
        if (seleccionada < 0) {
            Herramientas.Error("Primero seleccione el articulo a eliminar", "No has seleccionado un articulo");
        }else{
            factura.removeDetalle(seleccionada);
            ActualizaTabla();
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void FacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturarActionPerformed
        if (!Total.getText().equals("0")) {
            if (!Monto_Paga.getText().equals("")&&Integer.valueOf(Monto_Paga.getText())>=factura.getTotal()) {
                pago = Integer.valueOf(Monto_Paga.getText());
                Util.GuardaFactura(factura);
                MostrarFactura(factura);
            }else 
                Herramientas.Error("El monto ingresado es insuficiente para cancelar la factura", "Monto insuficiente");
        }else
            Herramientas.Error("Primero ingrese un articulo", "No has ingresado un articulo");
    }//GEN-LAST:event_FacturarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDialogFactura.dispose();
        VENTANA.CargarPanel(new Ventas());
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void MostrarFactura(Factura factura){
        DateFormat  dia,hora;
        dia = new SimpleDateFormat("dd/MM/yyyy");
        hora = new SimpleDateFormat("hh:mm:ssaa");
        String mensaje = "Recibo No:\t"+factura.getCod_Factura()+
                "\nFecha: "+dia.format(factura.getFecha())+"\tHora: "+hora.format(factura.getFecha())+
                "\nCliente:\n"+factura.getClient().getNombre()+" "+factura.getClient().getApellido1()+" "+factura.getClient().getApellido2()+
                "\nCedula:\t"+factura.getClient().getCedula()+
                "\n\n---------------------------------------"+
                "\n          Detalle del Recibo"+
                "\n---------------------------------------"+
                "\nCant Libro\t\t\t Monto\n";
        
        for (Detalle detalle : factura.getDetalles()) {
            char[] cadena = "                           ".toCharArray();
            int largo = (detalle.getLibro().getTitulo().length()<27)?detalle.getLibro().getTitulo().length():27;
            String uno = detalle.getLibro().getTitulo().substring(0, largo);
            System.arraycopy(uno.toCharArray(), 0, cadena, 0, uno.toCharArray().length);
            mensaje+= detalle.getUnidades()+"  "+String.valueOf(cadena)+"  ₡"+detalle.getTotal()+"\n";
        }
        mensaje+="\n---------------------------------------"+
                "\nMontos:"+
                "\n\tSubTotal:\t\t₡"+factura.getSubtotal()+
                "\n\tImpuesto:\t\t₡"+factura.getIV()+
                "\n\tTotal:   \t\t₡"+factura.getTotal()+
                "\n---------------------------------------"+
                "\n---------------------------------------"+
                "\nForma de Pago:"+
                "\n\tEfectivo:\t\t₡"+pago+
                "\n\tVuelto:  \t\t₡"+(pago-factura.getTotal())+
                "\n---------------------------------------\n"+
                "\n      Para reclamos o devoluciones\n      debe presentarse la factura\n      Muchas gracias por su compra";
        int renglones = mensaje.split("\n").length;
        int i = 0;
        for (String s: mensaje.split("\n")) {
            if (i<s.length()) {
                i=s.length();
            }
        }
        i+=6;
        area.setRows(renglones);
        area.setColumns(i);
        area.setText(mensaje);
        jDialogFactura.setMinimumSize(new Dimension(350, renglones*19+170));
        jDialogFactura.setVisible(true);
    }
    private void ActualizaTabla(){
        DefaultTableModel modelo = LimpiarTabla();
        factura.getDetalles().forEach((d) -> {
            modelo.addRow(new String[]{d.getLibro().getTitulo(),""+d.getCosto_Unitario(),""+d.getUnidades(),""+d.getTotal()});
        });
        Detalle.setModel(modelo);
    }
    
    private DefaultTableModel LimpiarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) Detalle.getModel();
        int filas = modelo.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }
        Detalle.setModel(modelo);
        return modelo;
    }
    
    private void mostrar(){
        jPanel4.setVisible(true);
        new Thread() {                                                          
            @Override
            public void run() {
                for (int i = -346; i <= 90; i++) {   
                    try {
                        if (i%2==0){Thread.sleep(2);}                      
                        jPanel4.setLocation(jPanel4.getX(), i);           
                    } catch (InterruptedException e) {
                        jPanel4.setLocation(jPanel4.getX(), -346);
                        break;                                                  
                    }                                                          
                }
                add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 300, 416));
                jPanel1.setVisible(false);
            }
        }.start();
    }
    
    private void ocultar(){
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 300, 416));
        jPanel1.setVisible(true);
        new Thread() {                                                          
            @Override
            public void run() {
                for (int i = 90; i >= -346; i--) {   
                    try {
                        if (i%2==0){Thread.sleep(2);}                      
                        jPanel4.setLocation(jPanel4.getX(), i);           
                    } catch (InterruptedException e) {
                        jPanel4.setLocation(jPanel4.getX(), 90);
                        break;                                                  
                    }                                                          
                }
                jPanel4.setVisible(false);
            }
        }.start();
    }
    
    private void initComponent() {
        jDialogFactura.setLocationRelativeTo(null);
        IniciarHilos();
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField Apellido1;
    private javax.swing.JTextField Apellido2;
    private javax.swing.JButton Cancelar;
    private javax.swing.JSpinner Cantidad;
    private javax.swing.JTextField Cedula;
    private javax.swing.JTable Detalle;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Facturar;
    private javax.swing.JLabel Hora;
    private javax.swing.JTextField ISBN;
    private javax.swing.JLabel Impuesto;
    private javax.swing.JTextField Monto_Paga;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton Registrar;
    private javax.swing.JLabel Subtotal;
    private javax.swing.JFormattedTextField Telefono;
    private javax.swing.JLabel Total;
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialogFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private Cliente cli;
    private Factura factura;
    private int pago;

    private void IniciarHilos() {
        DateFormat hora = new SimpleDateFormat("hh:mm:ss aa");
        new Thread(){
            @Override
            public void run() {
                do {
                    if (Util.getClienteDefault()!=null) {
                        cli = Util.getClienteDefault();
                        break;
                    } else {
                        try {
                            sleep(100);
                        } catch (InterruptedException e) {
                            break;
                        }
                    }
                } while (true);
                factura = Util.ObtenerFactura();
                factura.setClient(cli);
                do {
                    try {
                        Impuesto.setText(""+factura.getIV());
                        Subtotal.setText(""+factura.getSubtotal());
                        Total.setText(""+factura.getTotal());
                        Hora.setText(hora.format(new Date()));
                        sleep(500);
                    } catch (InterruptedException ex) {}
                } while (true);
            }
        }.start();
    }
}
