/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author David
 */
public class Vista extends javax.swing.JPanel {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        SubTitulo = new javax.swing.JLabel();
        Codigo = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(530, 230));
        setMinimumSize(new java.awt.Dimension(530, 230));
        setPreferredSize(new java.awt.Dimension(530, 230));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 310, 30));

        Cantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cantidad.setForeground(new java.awt.Color(255, 255, 255));
        Cantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 145, 310, 24));

        Precio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Precio.setForeground(new java.awt.Color(255, 255, 255));
        Precio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 310, 24));

        SubTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubTitulo.setForeground(new java.awt.Color(255, 255, 255));
        SubTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(SubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 310, 24));

        Codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Codigo.setForeground(new java.awt.Color(255, 255, 255));
        Codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 310, 24));

        Imagen.setMaximumSize(new java.awt.Dimension(120, 180));
        Imagen.setMinimumSize(new java.awt.Dimension(120, 180));
        Imagen.setPreferredSize(new java.awt.Dimension(120, 180));
        add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 180));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FondoList.png"))); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 230));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel SubTitulo;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getCantidad() {
        return Cantidad;
    }

    public void setCantidad(javax.swing.JLabel Cantidad) {
        this.Cantidad = Cantidad;
    }

    public javax.swing.JLabel getCodigo() {
        return Codigo;
    }

    public void setCodigo(javax.swing.JLabel Codigo) {
        this.Codigo = Codigo;
    }

    public javax.swing.JLabel getFondo() {
        return Fondo;
    }

    public void setFondo(javax.swing.JLabel Fondo) {
        this.Fondo = Fondo;
    }

    public javax.swing.JLabel getImagen() {
        return Imagen;
    }

    public void setImagen(javax.swing.JLabel Imagen) {
        this.Imagen = Imagen;
    }

    public javax.swing.JLabel getPrecio() {
        return Precio;
    }

    public void setPrecio(javax.swing.JLabel Precio) {
        this.Precio = Precio;
    }

    public javax.swing.JLabel getSubTitulo() {
        return SubTitulo;
    }

    public void setSubTitulo(javax.swing.JLabel SubTitulo) {
        this.SubTitulo = SubTitulo;
    }

    public javax.swing.JLabel getTitulo() {
        return Titulo;
    }

    public void setTitulo(javax.swing.JLabel Titulo) {
        this.Titulo = Titulo;
    }
    
    public void NoSeleccionada(){
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FondoList.png")));
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        SubTitulo.setForeground(new java.awt.Color(255, 255, 255));
        Codigo.setForeground(new java.awt.Color(255, 255, 255));
        Cantidad.setForeground(new java.awt.Color(255, 255, 255));
        Precio.setForeground(new java.awt.Color(255, 255, 255));
    }
    
    public void Seleccionada(){
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FondoList2.png")));
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        SubTitulo.setForeground(new java.awt.Color(0, 0, 0));
        Codigo.setForeground(new java.awt.Color(0, 0, 0));
        Cantidad.setForeground(new java.awt.Color(0, 0, 0));
        Precio.setForeground(new java.awt.Color(0, 0, 0));
    }
}
