/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import libreria.Libro;
import libreria.Util;

/**
 *
 * @author David
 */
public class VisualizarLibros extends javax.swing.JPanel {

    /**
     * Creates new form Default
     */
    public VisualizarLibros() {
        initComponents();
        initComponent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        NResultados = new javax.swing.JLabel();
        infoEditorial = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        infoClasificacion = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        infoAño = new javax.swing.JLabel();
        infoEdicion = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        infoEstanteria = new javax.swing.JLabel();
        infoPaginas = new javax.swing.JLabel();
        infoCaratura = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoDescripcion = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        infoAutores = new javax.swing.JList<>();
        infoTemas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        BuscarTodos = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Autor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Editorial = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Tema = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Categoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Año = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        ISBN = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setMaximumSize(new java.awt.Dimension(900, 579));
        setMinimumSize(new java.awt.Dimension(900, 579));
        setPreferredSize(new java.awt.Dimension(900, 579));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(130, 66, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NResultados.setBackground(new java.awt.Color(130, 66, 0));
        NResultados.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NResultados.setForeground(new java.awt.Color(255, 255, 255));
        NResultados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NResultados.setOpaque(true);
        jPanel2.add(NResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 460));

        infoEditorial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        infoEditorial.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(infoEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 145, 28));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Editorial: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 145, 28));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Clasificación: ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 40, 145, 28));

        infoClasificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        infoClasificacion.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(infoClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 145, 28));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("N°Edicion: ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, 145, 28));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Año: ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, 145, 28));

        infoAño.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        infoAño.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(infoAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 145, 28));

        infoEdicion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        infoEdicion.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(infoEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 145, 28));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("Tipo Caratura: ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 130, 145, 28));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("N°Paginas: ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 160, 145, 28));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("Estanteria: ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 190, 145, 28));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel18.setText("Temas: ");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 220, 145, 28));

        infoEstanteria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        infoEstanteria.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(infoEstanteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 145, 28));

        infoPaginas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        infoPaginas.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(infoPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 145, 28));

        infoCaratura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        infoCaratura.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(infoCaratura, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 145, 28));

        infoDescripcion.setBackground(new java.awt.Color(130, 66, 0));
        infoDescripcion.setColumns(20);
        infoDescripcion.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        infoDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        infoDescripcion.setRows(5);
        jScrollPane2.setViewportView(infoDescripcion);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 376, 290, 80));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Autores");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 250, 290, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Descripción");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 360, 290, -1));

        infoAutores.setBackground(new java.awt.Color(130, 66, 0));
        infoAutores.setForeground(new java.awt.Color(255, 255, 255));
        infoAutores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(infoAutores);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 270, 290, 80));

        infoTemas.setBackground(new java.awt.Color(130, 66, 0));
        infoTemas.setForeground(new java.awt.Color(255, 255, 255));
        infoTemas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(infoTemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 145, 28));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 300, 460));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Lista);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 530, 460));

        BuscarTodos.setText("Todos");
        BuscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTodosActionPerformed(evt);
            }
        });
        add(BuscarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 100, -1));

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 100, -1));

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda con Filtro", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Autor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 16, 125, -1));

        jLabel1.setText("Autor:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 20, -1, -1));

        jLabel2.setText("Editorial:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 52, -1, -1));

        Editorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(Editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 44, 125, -1));

        jLabel3.setText("Tema:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 20, -1, -1));

        Tema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(Tema, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 16, 125, -1));

        jLabel4.setText("Categoria:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 52, -1, -1));

        Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 44, 125, -1));

        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 20, -1, -1));

        jLabel6.setText("Año:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 48, -1, -1));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 17, 122, -1));

        try {
            Año.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Año.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jPanel1.add(Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 45, 122, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 560, 80));

        jPanel3.setBackground(new java.awt.Color(247, 247, 247));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda por ISBN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 200, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void ListaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMousePressed
        NResultados.setVisible(false);
        Especificacion(LIBROS.get(Lista.getSelectedIndex()));
        //System.out.println(Lista.getSelectedIndex());
        //System.out.println((String)( (Object [] ) Lista.getSelectedValue()) [1]);
    }//GEN-LAST:event_ListaMousePressed

    private void BuscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTodosActionPerformed
        LIBROS = Util.getLibroTodos();
        CargarLista();
    }//GEN-LAST:event_BuscarTodosActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if (ISBN.getText().equals("")) {
            Filtros();
        }else{
            LIBROS = Util.getLibroISBN(ISBN.getText().trim());
            CargarLista();
        }
    }//GEN-LAST:event_BuscarActionPerformed
    
    private void initComponent() {
        check = new boolean[]{false,false,false,false,false,false};
        Autor.setModel(new javax.swing.DefaultComboBoxModel<>(Util.getAutores()));
        Editorial.setModel(new javax.swing.DefaultComboBoxModel<>(Util.getEditoriales()));
        Tema.setModel(new javax.swing.DefaultComboBoxModel<>(Util.getTemas()));
        Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(Util.getCategorias()));
        LIBROS = Util.getLibroTodos();
        CargarLista();
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Autor;
    private javax.swing.JFormattedTextField Año;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton BuscarTodos;
    private javax.swing.JComboBox<String> Categoria;
    private javax.swing.JComboBox<String> Editorial;
    private javax.swing.JTextField ISBN;
    private javax.swing.JList<String> Lista;
    private javax.swing.JLabel NResultados;
    private javax.swing.JTextField Nombre;
    private javax.swing.JComboBox<String> Tema;
    private javax.swing.JList<String> infoAutores;
    private javax.swing.JLabel infoAño;
    private javax.swing.JLabel infoCaratura;
    private javax.swing.JLabel infoClasificacion;
    private javax.swing.JTextArea infoDescripcion;
    private javax.swing.JLabel infoEdicion;
    private javax.swing.JLabel infoEditorial;
    private javax.swing.JLabel infoEstanteria;
    private javax.swing.JLabel infoPaginas;
    private javax.swing.JComboBox<String> infoTemas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Libro> LIBROS;
    private boolean[] check;
    
    public class Renderer implements javax.swing.ListCellRenderer, javax.swing.Renderer{
        
        private Vista vista;
        
        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            //Modelo model = (Modelo) list.getModel();
            vista = new Vista();
            Libro l = (Libro) value;
            vista.getImagen().setIcon(new ImageIcon(l.getImagen().getImage().getScaledInstance(120, 180, 0)));
            vista.getTitulo().setText("Titulo: "+l.getTitulo());
            vista.getSubTitulo().setText("SubTitulo: "+l.getSubtitulo());
            vista.getCodigo().setText("Codigo: "+l.getIbsn());
            vista.getCantidad().setText("Cantidad: "+l.getEjemplares().getCantidad_Almacenada());
            vista.getPrecio().setText("Precio: "+l.getPrecio());
            if(!isSelected){
                vista.NoSeleccionada();
            }else{
                vista.Seleccionada();
            }
            return vista;
        }

        @Override
        public void setValue(Object aValue, boolean isSelected) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public Component getComponent() {
            return vista;
        }
    }
    
    public class Modelo extends DefaultListModel{
        public Modelo() {
            LIBROS.forEach((l) -> {
                this.addElement(l);
            });
        }
        @Override
        public int getSize() { return LIBROS.size(); }
       /* @Override
        public String getElementAt(int i) { return LIBROS.get(i).getTexto(); }*/
    }
    
    private void CargarLista() {
        Modelo newrnodel = new Modelo();
        Renderer newrenderer = new Renderer();
        Lista.setCellRenderer(newrenderer);
        Lista.setVisibleRowCount(2);
        Lista.setModel(newrnodel);
        NResultados.setVisible(true);
        NResultados.setText("Resultados: "+LIBROS.size());
        Autor.setSelectedIndex(0);
        Editorial.setSelectedIndex(0);
        Tema.setSelectedIndex(0);
        Categoria.setSelectedIndex(0);
        Nombre.setText("");
        Año.setText("");
        ISBN.setText("");
    }
    
    private void Filtros(){
        int[] index = new int[]{Autor.getSelectedIndex()-1,Editorial.getSelectedIndex()-1,Tema.getSelectedIndex()-1,Categoria.getSelectedIndex()-1}; 
        String[] s = new String[]{Nombre.getText().trim(),Año.getText().trim()};
        check[0]=!(Autor.getSelectedIndex()==0);
        check[1]=!(Editorial.getSelectedIndex()==0);
        check[2]=!(Tema.getSelectedIndex()==0);
        check[3]=!(Categoria.getSelectedIndex()==0);
        check[4]=!(Nombre.getText().equals(""));
        check[5]=!(Año.getText().trim().equals(""));
        LIBROS = Util.getFiltro(check, index, s);
        CargarLista();
    }
    
    private void Especificacion(Libro l){
        infoDescripcion.setText(l.getDescripcion());
        infoAño.setText(" "+l.getAño());
        infoCaratura.setText(" "+l.getCaratura());
        infoClasificacion.setText(" "+l.getCategoria().getNombre());
        infoEdicion.setText(" "+l.getNedicion());
        infoEditorial.setText(" "+l.getEditorial().getNombre());
        infoEstanteria.setText(" "+l.getNestanteria());
        infoPaginas.setText(" "+l.getNpaginas());
        String[] s = new String[l.getListaTemas().size()];
        for (int i = 0; i < s.length; i++) {
            s[i]=l.getListaTemas().get(i).getNombre();
        }
        infoTemas.setModel(new javax.swing.DefaultComboBoxModel<>(s));
        String[] m = new String[l.getListaAutores().size()];
        for (int i = 0; i < m.length; i++) {
            m[i]=l.getListaAutores().get(i).getNombre();
        }
        infoAutores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = m;
            @Override
            public int getSize() { return strings.length; }
            @Override
            public String getElementAt(int i) { return strings[i]; }
        });
    }
}
